name: build

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build-amd64:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: dotnet publish
      shell: cmd
      run: |
        dotnet publish -o bin\publish -c Release -r win-x64
    - name: artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: LenovoCustomLogo
        # Directory containing files to upload
        path: bin/publish
    - name: prerelease
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "ci-build"
        prerelease: true
        title: "Latest Development Build"
        files: |
          bin/publish/LenovoCustomLogo.exe
          bin/publish/LenovoCustomLogo.pdb
