name: build

permissions:
  contents: write

on:
  workflow_dispatch:
  push:

jobs:
  build-amd64:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
        include-prerelease: true
    - name: dotnet publish
      run: |
        dotnet publish -o out/ -c Release --self-contained
    - name: artifact
      uses: actions/upload-artifact@v4
      with:
        # Artifact name
        name: LenovoCustomLogo-${{ matrix.os }}
        # Directory containing files to upload
        path: out
    - name: prerelease
      if: github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ci-build
        files: out/*
        fail_on_unmatched_files: false
